---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-15.04
    driver:
      customize:
        memory: 1024
      network:
        - ['private_network', {ip: '192.168.33.33'}]
      vm_hostname: dc.mysubdomain.myorg.com
  - name: windows-2012R2
    driver:
      network:
        - ["forwarded_port", {guest: 3389, host: 3389}]
        - ['private_network', {ip: '192.168.33.34'}]
    driver_config:
      box: mwrock/Windows2012R2
      communicator: winrm
      vm_hostname: mywinhost
    transport:
      name: winrm


suites:
  - name: dc
    excludes:
      - windows-2012R2
    run_list:
      - recipe[samplewinsystem::dc]
    attributes:
  - name: default
    excludes:
      - ubuntu-15.04
    run_list:
      - recipe[samplewinsystem::default]
    attributes:
